// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKAoMELxNzzHOK-QK4yo10uQq93VpUzq8',
    appId: '1:261751806849:web:c467df9ca96eb45bc5e680',
    messagingSenderId: '261751806849',
    projectId: 'loot-bazaar-51965',
    authDomain: 'loot-bazaar-51965.firebaseapp.com',
    storageBucket: 'loot-bazaar-51965.appspot.com',
    measurementId: 'G-WYV4KKJVSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-s2zgjqYxWM6FgJY_v1jUrnjiGWTsZc',
    appId: '1:261751806849:android:5d3dd95826c8ae4ec5e680',
    messagingSenderId: '261751806849',
    projectId: 'loot-bazaar-51965',
    storageBucket: 'loot-bazaar-51965.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Wqmz6kuTHLtjhsZCZuv8xYTH56Sf9Qo',
    appId: '1:261751806849:ios:007bc80d4abcfaf5c5e680',
    messagingSenderId: '261751806849',
    projectId: 'loot-bazaar-51965',
    storageBucket: 'loot-bazaar-51965.appspot.com',
    iosBundleId: 'com.example.lootBazar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Wqmz6kuTHLtjhsZCZuv8xYTH56Sf9Qo',
    appId: '1:261751806849:ios:007bc80d4abcfaf5c5e680',
    messagingSenderId: '261751806849',
    projectId: 'loot-bazaar-51965',
    storageBucket: 'loot-bazaar-51965.appspot.com',
    iosBundleId: 'com.example.lootBazar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKAoMELxNzzHOK-QK4yo10uQq93VpUzq8',
    appId: '1:261751806849:web:aa76a3a14499cf84c5e680',
    messagingSenderId: '261751806849',
    projectId: 'loot-bazaar-51965',
    authDomain: 'loot-bazaar-51965.firebaseapp.com',
    storageBucket: 'loot-bazaar-51965.appspot.com',
    measurementId: 'G-C74CKYZ1W3',
  );
}
